import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar';
import { NextAuthProvider } from './providers';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next-Auth',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <div className="max-w-3xl mx-auto">
          <Navbar />
        {children}


        </div>
        </NextAuthProvider>
        
        </body>
    </html>
  )
}
